### ISSUE TITLE
Upsert, Electron & Bind

### ISSUE THREAD

**Issue by injectless** [pouchdb/upsert#23] opened 2016-07-04 04:23 UTC
Hi everyone!
I'm using this script in an Electron App, for store HTML as the user is typing.
Apparently, everything is OK,

But, a few minutes ago, I wrote a very long text, and my PC just frozen. Confident, I restarted and half the content was gone. Everything was/is working well, I'm just curious, this wasn't supposed to happen if the content is binded as type.

Do you recommend using this to achieve such functionality?

**Comment by nolanlawson** [comment] 2016-07-05 03:11
Hi @injectless, if you can provide a test case to reproduce, that would be very helpful. It's difficult to say exactly what the cause of your crash was without details. Which adapter were you using? Are you sure it's because of pouchdb-upsert?

**Comment by injectless** [comment] 2016-07-12 18:12
I tried to reproduce it but apparently it's not happen anymore, though I am not settled with this. I'm positive it will happen when I'm actually writing something I care about just to piss me off.

I still have a situation, where the bind takes place.
For each word you write, for each letter, PouchDB saves a revision. _I really don't know if using upsert, **which's creating a new revision every time you press a key**, is a good idea_.
I'm thinking of adding some kind of setTimeout(), but maybe you have a better idea on how to handle this.
![screenshot_2016-07-12_15-10-27](https://cloud.githubusercontent.com/assets/12424545/16778104/cd2c40e4-4842-11e6-9c8c-98dad880070b.png)

Look at the **Value** row.

**Comment by nolanlawson** [comment] 2016-07-13 01:32
Yeah, if you’re making a modification for every single keystroke, then I’m not surprised that it crashed. PouchDB is really not designed for that kind of workload.

Instead of setTimeout I would recommend using a debounce; lodash-debounce is a very good one.

**Comment by nolanlawson** [comment] 2016-07-13 01:55
Closing, please reopen if you still think this is a bug in pouchdb-upsert, cheers.

**Closed by nolanlawson** 2016-07-13 01:55 UTC

**Comment by injectless** [comment] 2016-07-13 05:41
Nah, I'm sure it was my mistake.
I leave this code here, in case it helps anyone:

Angular has debounce as standard.
`ng-model-options="{ debounce: 500 }"`

Scope will not be update until 500ms after the last keystroke.
